services:

  nginx:
    build: ./requirements/nginx/

    image: nginx

    container_name: NGINX

    networks:
      - nginx-wp

    restart: unless-stopped

    ports:
      - "443:443"

    depends_on:
      - wordpress

    volumes:
      - wp_data:/var/www/html

  mariadb:
      build: ./requirements/mariadb/

      image: mariadb

      container_name: MARIADB

      networks:
        - db-wp

      env_file:
        - .env

      restart: unless-stopped
        
      volumes:
        - mariadb_data:/var/lib/mysql

  wordpress:
      build: ./requirements/wordpress/

      image: wordpress
      
      container_name: WORDPRESS

      networks:
        - nginx-wp
        - db-wp

      depends_on:
        - mariadb

      env_file:
        - .env

      restart: unless-stopped

      volumes:
        - wp_data:/var/www/html

networks:
  nginx-wp:
    driver: bridge
  db-wp:
    driver: bridge


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vgarcia/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vgarcia/data/wordpress
