services:

  nginx:
    build: ./requirements/nginx/

    image: nginx

    container_name: NGINX

    networks:
      - inception
    ports:
      - "443:443"

# comment link le port 9000 a nginx ?

# comment link le port 3306 a wp ?
  mariadb:
      build: ./requirements/mariadb/

      image: mariadb

      container_name: MARIADB

      networks:
        - inception

      env_file:
        - .env

      ports:
        - "3306:3306"

      volumes:
        - ./requirements/mariadb/config:/var/lib/mysql/

  # wordpress:
  #     build: ./requirements/wordpress/

  #     container_name: WORDPRESS

  #     depends_on:
  #       - mariadb
  #     environment:
  #       - .env
  #     volumes:
  #       - ./requirements/wordpress/:/var/lib/mysql/       # database volume     a voir pour le mettre dans home/vgarcia/ y a un bail comme ca
  #     networks:
  #       - inception

networks:
  inception:
    driver: bridge
