services:

  nginx:
    build: ./requirements/nginx/

    image: nginx

    container_name: NGINX

    networks:
      - inception

    restart: unless-stopped

    ports:
      - "443:443"

    depends_on:
      - wordpress

    volumes:
      - wp_data:/var/www/html

  mariadb:
      build: ./requirements/mariadb/

      image: mariadb

      container_name: MARIADB

      networks:
        - inception

      env_file:
        - .env

      restart: unless-stopped
        
      ports:
        - "3306:3306"

      volumes:
        - mariadb_data:/var/lib/mysql

  wordpress:
      build: ./requirements/wordpress/

      image: wordpress
      
      container_name: WORDPRESS

      networks:
        - inception

      depends_on:
        - mariadb

      env_file:
        - .env

      restart: unless-stopped

      ports:
        - "9000:9000"
      volumes:
        - wp_data:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vgarcia/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vgarcia/data/wordpress
