services:

  nginx:
    build: ./requirements/nginx/

    image: nginx

    container_name: NGINX

    networks:
      - inception

    restart: unless-stopped

    ports:
      - "443:443"

  mariadb:
      build: ./requirements/mariadb/

      image: mariadb

      container_name: MARIADB

      networks:
        - inception

      env_file:
        - .env

      restart: unless-stopped
        
      ports:
        - "3306:3306"

      volumes:
        - mariadb_data:/var/lib/mysql

  wordpress:
      build: ./requirements/wordpress/

      container_name: WORDPRESS

      depends_on:
        - mariadb

      env_file:
        - .env

      restart: unless-stopped

      volumes:
        - ./requirements/wordpress/:/var/www/html

      networks:
        - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local

