services:

  nginx:
    build: ./requirements/nginx/

    image: nginx:1.24.0

    container_name: NGINX

    networks:
      - inception
    ports:
      - "443:443"

# comment link le port 9000 a nginx ?

# comment link le port 3306 a wp ?
  mariadb:
      build: ./requirements/mariadb/

      container_name: MARIADB

      networks:
        - inception
      environment:
        - .env

      volumes:
        - ./requirements/mariadb/config:/config

  wordpress:
      build: ./requirements/wordpress/

      container_name: WORDPRESS

      depends_on:
        - mariadb
      environment:
        - .env
      volumes:
        - ./requirements/wordpress/:/var/lib/mariadb/       # database volume     a voir pour le mettre dans home/vgarcia/ y a un bail comme ca
      networks:
        - inception

networks:
  inception:
    driver: bridge            # qlq chose comme ca pour setup le network