CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};

CREATE USER ${MARIADB_USER}@'%' IDENTIFIED BY ${MARIADB_PASSWD};
CREATE USER ${MARIADB_ADMIN_USER}@'%' IDENTIFIED BY ${MARIADB_ADMIN_PASSWD};

GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO ${MARIADB_ADMIN_USER}@'%';
